apiVersion : apps/v1
kind: Deployment
metadata:
  name: snehgoyalwebapiaks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: snehgoyalwebapiaks 
    spec:
      containers:
        - name: snehgoyalwebapiaks 
          image: myakspocacr.azurecr.io/snehgoyalwebapiaks
          ports:
          - containerPort: 80
